name = "ClimaReproducibilityTests"
uuid = "e0c89595-00ba-42a9-9f9b-061ef3dc23a1"
authors = ["Climate Modeling Alliance"]
version = "0.1.0"

[deps]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"

[compat]
OrderedCollections = "1.6"
PrettyTables = "2"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

